---
title: "[21.09.25] Golang_스터디 CH_23"
date: 2021-09-25 21:00:28 -0400
toc: true
toc_sticky: true
categories: Golang_Study
---

# 💭 에러 핸들링

##  1. 에러 반환

에러를 처리하는 가장 기본 방식은 에러를 반환하고 알맞게 처리하는 방식이다.    
err이 nil이면 성공, 아니면 에러가 발생한 것으로, 에러가 나면 이를 반환하면 된다.         

### 📌 <u>사용자 에러 반환</u>

직접 에러를 만들어서 반환할 수도 있다.   

1. `fmt.Errof()` 함수를 사용해 에러를 반환
2. `errors` 패키지의 `New()`함수를 이용해서 error를 생성할 수도 있음! 인수로 문자열을 입력하면 인수와 같은 메시지를 갖는 `error`를 생성해서 반환한다.    
   
## 2. 에러 타입

error는 사실 인터페이스로, 문자열을 반환하는 Error() 메서드로 구성되어 있다.    

즉, 어떤 타입이든 문자열을 반환하는 Error() 메서드를 포함하고 있다면 에러로 사용할 수 있다.  

### 📌 <u>에러 랩핑</u>

 때로는 에러를 감싸서 새로운 에러를 만들어야 할 수도 있다.    
 
 어떻게 에러를 감싸고, 어떻게 에러 안에 숨겨진 에러를 풀어내는지 알아보자.         
 
   ```go
fmt.Errorf("Error: %w", err)
   ```  

위와 같이 %w를 사용하면 err를 감싸서 새로운 에러를 반환하게 되고, 다른 정보와 함수에서 발생한 에러까지 에러 하나로 반환할 수 있게 됨!    

이렇게 감싸진 에러를 다시 꺼내올 때는 `errors` 패키지의 `As()` 함수를 이용하면 된다.     


##  3. 패닉

**패닉<sup>panic</sup>은 <u>프로그램을 정상 진행시키기 어려운 상황을 만났을 때 프로그램 흐름을 중지시키는 기능</u>**이다.     
Go언어는 내장 함수 panic()으로 패닉 기능을 제공한다.    

프로그램을 수행하다 보면 예기치 못한 에러에 직면하기도 하는데, 이럴 때는 프로그램을 강제 종료해서 문제를 빠르게 파악하는 편이 나을 수도 있음!    
panic() 함수를 사용하면 문제 발생 시점에 바로 종료시켜 빠르게 문제 발생 시점을 알수 있으며, 버그 수정에 유용하다.       

### 📌 [1] <u>패닉 생성</u>

패닉은 내장 함수 `panic()`을 사용해서 발생시킬 수 있다.    

   ```go
func panic(interface{})
   ```

panic() 내장 함수의 인수로는 interface{} 타입 즉 모든 타입을 사용할 수 있음!   

### 📌 [2] <u>패닉 전파 그리고 복구</u>

사용자에게 프로그램이 배포된 후에는 복구할 수 있는 패닉에 한해 복구를 시도하는 것이 좋다.   

panic()은 호출 순서를 거슬러 올라가며 전파되며, 어느 단계에서든 패닉은 복구된 시점부터 프로그램이 계속된다.   

recover() 함수를 호출하여 패닉 복구를 할 수 있으며, recover() 함수가 호출되는 시점에 패닉이 전파 중이면 panic 객체를 반환하고 그렇지 않으면 nil을 반환한다.    
    

### 📌 [3] <u>recover() 결과</u>

내장 함수 recover()는 발생한 panic 객체를 반환해준다.    
interface{} 타입으로 반환되므로, 실제로 사용하기 위해서는 타입 검사가 필수적이다.     
 
       
# 🌟 오늘의 핵심      

<div class="notice--primary" markdown="1">

1. error 인터페이스를 통해서 에러를 반환한다.          
  
2. errors.New() 또는 fmt.Errorf()를 사용해 에러를 만들 수 있다. 또는 Error() 메서드를 정의해서 나만의 error 객체를 만들 수 있다.            

3. 에러를 감싸고 다시 풀어서 에러를 처리할 수 있다.              

4. panic() 함수로 프로그램을 즉시 종료하고 recover() 함수로 복구할 수 있다.        

</div>

_


# 👩🏻‍💻 관련 추가 과제

## 1번

Q) 구글에 "golang 패키지명"을 적으면 Go 문서에서 해당 패키지 내용을 볼 수 있습니다. 다음은 os 패키지의 Open() 함수에 대한 정의이다. os 패키지의 Open() 함수는 에러가 발생할 때 어떤 타입의 에러를 반환하는지 주석을 보고 적어보세요.     

   ```go
// Open opens the named file for reading. If successful, methods on
// the returned file can be used for reading; the associated file
// descriptor has mode )_RODNLY.
// If there is an error, it will be of type *PathError.
func Open(name string) (*File, error) {
	return OpenFile(name, O_RDONLY, 0)
}
   ```
      

A) *os.PathError 타입

## 2번 

Q) 다음 예제의 출력 결과를 쓰세요.

   ```go
package main

import "fmt"

func Atoi(str string) (int, error) {
	rst := 0
	for _, r := range str {
		if r >= '0' && r <= '9' {
			rst *= 10
			rst += int(r - '0')
		} else {
			return 0, fmt.Errorf("숫자만 입력하세요. 문자:%c", r)
		}
	}
	return rst, nil
}

func main() {
	n, err := Atoi("34cd")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(n)
	}
}
   ```

A) 

   ```go
숫자만 입력하세요. 문자:c
   ```

## 3번 

Q) 다음 예제의 출력 결과를 쓰세요.            

   ```go
package main

import (
	"fmt"
)

func sum(nums ...int) int {
	if len(nums) == 0 {
		panic("nums should be not empty")
	}
	result := 0
	for _, v := range nums {
		result += v
	}
	return result
}

func PrintSum() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	fmt.Println(sum(1, 2, 3, 4, 5))
	fmt.Println(sum())
	fmt.Println(sum(1, 2, 3))
}

func main() {
	PrintSum()
	fmt.Println("end of main")
}

   ```
 

A) 

   ```go
15
nums should be not empty
end of main
   ```
